language: node_js
node_js:
- "lts/*"
env:
  global:
  - GH_REF: github.com/chad-autry/character-perspective-client
script:
- npm run build
after_success:
- chmod ugo+x ./deploy-gh-pages.sh
- ./deploy-gh-pages.sh
deploy:
   provider: npm
   email: "chad.autry@gmail.com"
   api_key: "$NPM_TOKEN"
   on:
     tags: true
